---
- name: test
  hosts: 
    - dev
  gather_facts: true
  become: true
  handlers:
  - name: restart_sshd
    service:
        name: sshd
        state: restarted
  tasks:
  - name: Create tux user
    user:
      name: tux
      state: present
      password: "{{ 'Password1' | password_hash('sha512') }}"
      update_password: on_create
      shell: /bin/bash

  - name: Edit SSHD Config
    lineinfile:
      path: /etc/ssh/sshd_config
      regexp: '^PasswordAuthentication '
      insertafter: '#PasswordAuthentication'
      line: 'PasswordAuthentication yes'
    notify: restart_sshd

  - name: Add sudo rights for tux
    copy:
      dest: /etc/sudoers.d/tux
      content: "tux ALL=(root) NOPASSWD: ALL"
      backup: true

  - name: try to create a vm with qemu
    community.libvirt.virt:
      command: define
      xml: "{{ lookup('template', 'vm_template.xml.j2') }}"
      autostart: true



